Baruch Spinoza
From Wikipedia, the free encyclopedia
"Spinoza" redirects here. For other uses, see Spinoza (disambiguation).
Baruch Spinoza
Spinoza.jpg
Born	24 November 1632
Amsterdam, Dutch Republic
Died	21 February 1677 (aged 44)
The Hague, Dutch Republic
Residence	Netherlands
Education	Talmud Torah of Amsterdam[1]
(withdrew)[2]
Alma mater	University of Leiden
(no degree)[3]
Era	17th-century philosophy
Region	Western philosophy
School	Rationalism, founder of Spinozism
Main interests
Ethics, epistemology, metaphysics, Hebrew grammar
Notable ideas
Pantheism, determinism, neutral monism, parallelism, intellectual and religious freedom, separation of church and state, criticism of Mosaic authorship of some books of the Hebrew Bible, political society as derived from power (not contract), affect, natura naturans/natura naturata
Influences[show]
Influenced[show]
Baruch Spinoza (/b?'ru?k sp?'no?z?/;[6] Dutch: [ba?'rux sp?'no?za?]; born Benedito de Espinosa, Portuguese: [b?n?'ðitu ð? ?pi'n?z?]; 24 November 1632 – 21 February 1677, later Benedict de Spinoza) was a Dutch philosopher of Sephardi/Portuguese origin.[5] By laying the groundwork for the 18th-century Enlightenment[7] and modern biblical criticism,[8] including modern conceptions of the self and the universe,[9] he came to be considered one of the great rationalists of 17th-century philosophy.[10] Along with René Descartes, Spinoza was a leading philosophical figure of the Dutch Golden Age. Spinoza's given name, which means "Blessed", varies among different languages. In Hebrew, it is written ???? ???????. His Portuguese name is Benedito "Bento" de Espinosa. In his Latin works, he used Latin: Benedictus de Spinoza.

Spinoza's magnum opus, Ethics, was published posthumously in 1677. The work opposed Descartes' philosophy on mind–body dualism, and earned Spinoza recognition as one of Western philosophy's most important thinkers. In the Ethics, "Spinoza wrote the last indisputable Latin masterpiece, and one in which the refined conceptions of medieval philosophy are finally turned against themselves and destroyed entirely".[11] Georg Wilhelm Friedrich Hegel said, "You are either a Spinozist or not a philosopher at all."[12] His philosophical accomplishments and moral character prompted philosopher Gilles Deleuze to name him "the 'prince' of philosophers."[13]

Spinoza was raised in a Portuguese Jewish community in Amsterdam. He developed highly-controversial ideas regarding the authenticity of the Hebrew Bible and the nature of the Divine. Jewish religious authorities issued a herem (???) against him, causing him to be effectively shunned by Jewish society at age 23. His books were also later put on the Catholic Church's Index of Forbidden Books.

Spinoza lived an outwardly-simple life as a lens grinder, turning down rewards and honours throughout his life, including prestigious teaching positions. He died at the age of 44 allegedly of a lung illness, perhaps tuberculosis or silicosis exacerbated by the inhalation of fine glass dust while grinding optical lenses. He is buried in the churchyard of the Christian Nieuwe Kerk in The Hague.[14]

Contents  [hide] 
1	Biography
1.1	Family and community origins
1.2	17th-century Netherlands
1.3	Early life
1.4	Expulsion from the Jewish community
1.5	Later life and career
1.6	Voorburg
1.7	Lens-grinding and optics
1.8	The Hague
1.9	Writings and correspondence
2	Philosophy
2.1	Substance, attributes, and modes
2.2	Ethical philosophy
2.3	Spinoza's "Ethics"
3	History of reception
3.1	Pantheist, panentheist, or atheist?
3.2	Comparison to Eastern philosophies
3.3	Spinoza's reception in the 19th and 20th centuries
3.4	Spinoza's religious criticism and its effect on the philosophy of language
3.5	Spinoza in literature, art, and popular culture
4	Bibliography
5	See also
6	References
7	Further reading
8	External links
Biography[edit]
Family and community origins[edit]
Spinoza's ancestors were of Sephardic Jewish descent and were a part of the community of Portuguese Jews that had settled in the city of Amsterdam in the wake of the Portuguese Inquisition (1536), which had resulted in forced conversions and expulsions from the Iberian peninsula.[15]

The Spinoza family ("de Espinosa" or "Espinosa" in Portuguese and in Spanish; it could also be spelled as "de Espinoza" or "Espinoza" in both languages) probably had its origins in Espinosa de los Monteros, near Burgos, or in Espinosa de Cerrato, near Palencia, both in Northern Castile, Spain. The family was expelled from Spain in 1492 and fled to Portugal. Portugal compelled them to convert to Catholicism in 1498.[16][17]

Attracted by the Decree of Toleration issued in 1579 by the Union of Utrecht, Portuguese "conversos" first sailed to Amsterdam in 1593 and promptly reconverted to Judaism.[18] In 1598 permission was granted to build a synagogue, and in 1615 an ordinance for the admission and government of the Jews was passed.[19] As a community of exiles, the Portuguese Jews of Amsterdam were highly proud of their identity.[19]

Spinoza's father was born roughly a century after this forced conversion in the small Portuguese city of Vidigueira, near Beja in Alentejo. When Spinoza's father was still a child, Spinoza's grandfather, Isaac de Spinoza, who was from Lisbon, took his family to Nantes in France. They were expelled in 1615 and moved to Rotterdam, where Isaac died in 1627.

Spinoza's father, Miguel (Michael), and his uncle, Manuel, then moved to Amsterdam where they resumed the practice of Judaism. Miguel was a successful merchant and became a warden of the synagogue and of the Amsterdam Jewish school.[19] He buried three wives and three of his six children died before reaching adulthood.[20]

17th-century Netherlands[edit]
Amsterdam and Rotterdam operated as important cosmopolitan centres where merchant ships from many parts of the world brought people of various customs and beliefs. This flourishing commercial activity encouraged a culture relatively tolerant of the play of new ideas, to a considerable degree sheltered from the censorious hand of ecclesiastical authority (though those considered to have gone "too far" might have gotten persecuted even in the Netherlands). Not by chance were the philosophical works of both Descartes and Spinoza developed in the cultural and intellectual background of the Dutch Republic in the 17th century.[21] Spinoza may have had access to a circle of friends who were unconventional in terms of social tradition, including members of the Collegiants.[22] One of the people he knew was Niels Stensen, a brilliant Danish student in Leiden;[23] others included Albert Burgh, with whom Spinoza is known to have corresponded.[24]

Early life[edit]

Map by Balthasar Florisz van Berckenrode (1625) with the present location of the Moses and Aaron church in white, but also the spot where Spinoza grew up.[25]

Spinoza lived where the Moses and Aaron Church is located now, and there is strong evidence that he may have been born there.[26]
Benedito de Espinoza was born on 24 November 1632 in the Jodenbuurt in Amsterdam, Netherlands. He was the second son of Miguel de Espinoza, a successful, although not wealthy, Portuguese Sephardic Jewish merchant in Amsterdam.[27] His mother, Ana Débora, Miguel's second wife, died when Baruch was only six years old.[28] Spinoza's mother tongue was Portuguese, although he also knew Hebrew, Spanish, Dutch, perhaps French, and later Latin.[29] Although he wrote in Latin, Spinoza learned the language only late in his youth.

Spinoza had a traditional Jewish upbringing, attending the Keter Torah yeshiva of the Amsterdam Talmud Torah congregation headed by the learned and traditional senior Rabbi Saul Levi Morteira. His teachers also included the less-traditional Rabbi Manasseh ben Israel, "a man of wide learning and secular interests, a friend of Vossius, Grotius, and Rembrandt".[30] While presumably a star pupil, and perhaps considered as a potential rabbi, Spinoza never reached the advanced study of the Torah in the upper levels of the curriculum.[31] Instead, at the age of 17, after the death of his elder brother, Isaac, he cut short his formal studies in order to begin working in the family importing business.[32]

In 1653, at age 20, Spinoza began studying Latin with Francis van den Enden (Franciscus van den Enden), a notorious free thinker, former Jesuit, and radical democrat who likely introduced Spinoza to scholastic and modern philosophy, including that of Descartes.[33] (A decade later, in the early 1660s, Van den Enden was considered to be a Cartesian and atheist,[34] and his books were put on the Catholic Index of Banned Books.)

Spinoza's father, Miguel, died in 1654 when Spinoza was 21. He duly recited Kaddish, the Jewish prayer of mourning, for eleven months as required by Jewish law.[35] When his sister Rebekah disputed his inheritance, he took her to court to establish his claim, won his case, but then renounced his claim in her favour.[36]

Spinoza adopted the Latin name Benedictus de Spinoza,[37] began boarding with Van den Enden, and began teaching in his school.[38] Following an anecdote in an early biography by Johannes Colerus,[39] he is said to have fallen in love with his teacher's daughter, Clara, but she rejected him for a richer student. (This story has been discounted on the basis that Clara Maria van den Enden was born in 1643 and would have been no more than about 18 years old when Spinoza left Amsterdam.[29] In 1671 she married Dirck Kerckring.)

During this period Spinoza also became acquainted with the Collegiants, an anti-clerical sect of Remonstrants with tendencies towards rationalism, and with the Mennonites who had existed for a century but were close to the Remonstrants.[40] Many of his friends belonged to dissident Christian groups which met regularly as discussion groups and which typically rejected the authority of established churches as well as traditional dogmas.[5]

Spinoza's break with the prevailing dogmas of Judaism, and particularly the insistence on non-Mosaic authorship of the Pentateuch, was not sudden; rather, it appears to have been the result of a lengthy internal struggle: "If anyone thinks my criticism [regarding the authorship of the Bible] is of too sweeping a nature and lacking sufficient foundation, I would ask him to undertake to show us in these narratives a definite plan such as might legitimately be imitated by historians in their chronicles... If he succeeds, I shall at once admit defeat, and he will be my mighty Apollo. For I confess that all my efforts over a long period have resulted in no such discovery. Indeed, I may add that I write nothing here that is not the fruit of lengthy reflection; and although I have been educated from boyhood in the accepted beliefs concerning Scripture, I have felt bound in the end to embrace the views I here express."[41]

Nevertheless, once branded as a heretic, Spinoza's clashes with authorities became more pronounced. For example, questioned by two members of his synagogue, Spinoza apparently responded that God has a body and nothing in scripture says otherwise.[36] He was later attacked on the steps of the synagogue by a knife-wielding assailant shouting "Heretic!" He was apparently quite shaken by this attack and for years kept (and wore) his torn cloak, unmended, as a souvenir.[36]

After his father's death in 1654, Spinoza and his younger brother Gabriel (Abraham)[35] ran the family importing business. The business ran into serious financial difficulties, however, perhaps as a result of the First Anglo-Dutch War. In March 1656, Spinoza filed suit with the Amsterdam municipal authorities to be declared an orphan in order to escape his father's business debts and so that he could inherit his mother's estate (which at first was incorporated into his father's estate) without it being subject to his father's creditors.[42] In addition, after having made substantial contributions to the Talmud Torah synagogue in 1654 and 1655, he reduced his December 1655 contribution and his March 1656 pledge to nominal amounts (and the March 1656 pledge was never paid).[43]

Spinoza was eventually able to relinquish responsibility for the business and its debts to his younger brother, Gabriel, and devote himself chiefly to the study of philosophy, especially the system expounded by Descartes, and to optics.

Expulsion from the Jewish community[edit]
On 27 July 1656, the Talmud Torah congregation of Amsterdam issued a writ of cherem (Hebrew: ????, a kind of ban, shunning, ostracism, expulsion, or excommunication) against the 23-year-old Spinoza.[36] The following document translates the official record of the censure:[44]

The Lords of the ma'amad, having long known of the evil opinions and acts of Baruch de Espinoza, have endeavoured by various means and promises, to turn him from his evil ways. But having failed to make him mend his wicked ways, and, on the contrary, daily receiving more and more serious information about the abominable heresies which he practised and taught and about his monstrous deeds, and having for this numerous trustworthy witnesses who have deposed and borne witness to this effect in the presence of the said Espinoza, they became convinced of the truth of the matter; and after all of this has been investigated in the presence of the honourable chachamin [sages], they have decided, with their consent, that the said Espinoza should be excommunicated and expelled from the people of Israel. By the decree of the angels, and by the command of the holy men, we excommunicate, expel, curse and damn Baruch de Espinoza, with the consent of God, Blessed be He, and with the consent of all the Holy Congregation, in front of these holy Scrolls with the six-hundred-and-thirteen precepts which are written therein, with the excommunication with which Joshua banned Jericho,[45] with the curse with which Elisha cursed the boys [46] and with all the curses which are written in the Book of the Law. Cursed be he by day and cursed be he by night; cursed be he when he lies down, and cursed be he when he rises up; cursed be he when he goes out, and cursed be he when he comes in. The Lord will not spare him; the anger and wrath of the Lord will rage against this man, and bring upon him all the curses which are written in this book, and the Lord will blot out his name from under heaven, and the Lord will separate him to his injury from all the tribes of Israel with all the curses of the covenant, which are written in the Book of the Law. But you who cleave unto the Lord God are all alive this day. We order that no one should communicate with him orally or in writing, or show him any favour, or stay with him under the same roof, or within four ells of him, or read anything composed or written by him.


Statue of Spinoza, near his house on the Paviljoensgracht in The Hague.
The Talmud Torah congregation issued censure routinely, on matters great and small, so such an edict was not unusual.[47] The language of Spinoza's censure is unusually harsh, however, and does not appear in any other censure known to have been issued by the Portuguese Jewish community in Amsterdam.[48] The exact reason for expelling Spinoza is not stated.[49] The censure refers only to the "abominable heresies that he practised and taught," to his "monstrous deeds," and to the testimony of witnesses "in the presence of the said Espinoza." There is no record of such testimony, but there appear to have been several likely reasons for the issuance of the censure.

First, there were Spinoza's radical theological views that he was apparently expressing in public. As philosopher and Spinoza biographer Steven Nadler puts it: "No doubt he was giving utterance to just those ideas that would soon appear in his philosophical treatises. In those works, Spinoza denies the immortality of the soul; strongly rejects the notion of a providential God—the God of Abraham, Isaac and Jacob; and claims that the Law was neither literally given by God nor any longer binding on Jews. Can there be any mystery as to why one of history's boldest and most radical thinkers was sanctioned by an orthodox Jewish community?"[50]

Second, the Amsterdam Jewish community was largely composed of former "conversos" who had fled from the Portuguese Inquisition within the previous century, with their children and grandchildren. This community must have been concerned to protect its reputation from any association with Spinoza lest his controversial views provide the basis for their own possible persecution or expulsion.[51] There is little evidence that the Amsterdam municipal authorities were directly involved in Spinoza's censure itself. But "in 1619, the town council expressly ordered [the Portuguese Jewish community] to regulate their conduct and ensure that the members of the community kept to a strict observance of Jewish law."[52] Other evidence makes it clear that the danger of upsetting the civil authorities was never far from mind, such as bans adopted by the synagogue on public wedding or funeral processions and on discussing religious matters with Christians, lest such activity might "disturb the liberty we enjoy."[53] Thus, the issuance of Spinoza's censure was almost certainly, in part, an exercise in self-censorship by the Portuguese Jewish community in Amsterdam.[54]

Third, it appears likely that Spinoza had already taken the initiative to separate himself from the Talmud Torah congregation and was vocally expressing his hostility to Judaism itself. He had probably stopped attending services at the synagogue, either after the lawsuit with his sister or after the knife attack on its steps. He might already have been voicing the view expressed later in his Theological-Political Treatise that the civil authorities should suppress Judaism as harmful to the Jews themselves. Either for financial or other reasons,[55] he had in any case effectively stopped contributing to the synagogue by March 1656. He had also committed the "monstrous deed," contrary to the regulations of the synagogue and the views of some rabbinical authorities (including Maimonides), of filing suit in a civil court rather than with the synagogue authorities[56]—to renounce his father's heritage, no less. Upon being notified of the issuance of the censure, he is reported to have said: "Very well; this does not force me to do anything that I would not have done of my own accord, had I not been afraid of a scandal."[57] Thus, unlike most of the censure issued routinely by the Amsterdam congregation to discipline its members, the censure issued against Spinoza did not lead to repentance and so was never withdrawn.

After the censure, Spinoza is said to have addressed an "Apology" (defence), written in Spanish, to the elders of the synagogue, "in which he defended his views as orthodox, and condemned the rabbis for accusing him of 'horrible practices and other enormities' merely because he had neglected ceremonial observances."[57] This "Apology" does not survive, but some of its contents may later have been included in his Theological-Political Treatise.[57] For example, he cited a series of cryptic statements by medieval Biblical commentator Abraham ibn Ezra intimating that some apparently anachronistic passages of the Pentateuch (i.e., "[t]he Canaanite was then in the land," Genesis 12:6, which ibn Ezra called a "mystery" and exhorted those "who understand[] it keep silent") were not of Mosaic authorship as proof that his own views had valid historical precedent.[41]

The most remarkable aspect of the censure may be not so much its issuance, or even Spinoza's refusal to submit, but the fact that Spinoza's expulsion from the Jewish community did not lead to his conversion to Christianity.[58] Spinoza kept the Latin (and so implicitly Christian) name Benedict de Spinoza, maintained a close association with the Collegiants, a Christian sect, even moved to a town near the Collegiants' headquarters, and was buried in a Christian graveyard—but there is no evidence or suggestion that he ever accepted baptism or participated in a Christian mass. Thus, by default, Baruch de Espinoza became the first secular Jew of modern Europe.[58]

In September 2012, the Portugees-Israëlietische Gemeente te Amsterdam asked the chief rabbi of their community Haham Pinchas Toledano to reconsider the cherem after consulting several Spinoza experts. However he declined to remove it, citing Spinoza's "preposterous ideas, where he was tearing apart the very fundamentals of our religion".[59]

Later life and career[edit]

Spinoza's house in Rijnsburg from 1661 to 1663, now a museum

Study room of Spinoza
Spinoza spent his remaining 21 years writing and studying as a private scholar.[5]

Spinoza believed in a "Philosophy of tolerance and benevolence"[60] and actually lived the life which he preached. He was criticized and ridiculed during his life and afterwards for his alleged atheism. However, even those who were against him "had to admit he lived a saintly life".[60] Besides the religious controversies, nobody really had much bad to say about Spinoza other than, "he sometimes enjoyed watching spiders chase flies".[60]

After the cherem, the Amsterdam municipal authorities expelled Spinoza from Amsterdam, "responding to the appeals of the rabbis, and also of the Calvinist clergy, who had been vicariously offended by the existence of a free thinker in the synagogue".[57] He spent a brief time in or near the village of Ouderkerk aan de Amstel, but returned soon afterwards to Amsterdam and lived there quietly for several years, giving private philosophy lessons and grinding lenses, before leaving the city in 1660 or 1661.[57]

During this time in Amsterdam, Spinoza wrote his Short Treatise on God, Man, and His Well-Being, which he never published in his lifetime—assuming with good reason that it might get suppressed. Two Dutch translations of it survive, discovered about 1810."[57]

Spinoza moved around 1660 or 1661 from Amsterdam to Rijnsburg, (near Leiden), the headquarters of the Collegiants.[61] In Rijnsburg, he began work on his Descartes' "Principles of Philosophy" as well as on his masterpiece, the Ethics. In 1663, he returned briefly to Amsterdam, where he finished and published Descartes' "Principles of Philosophy," the only work published in his lifetime under his own name, and then moved the same year to Voorburg.[62]

Voorburg[edit]
In Voorburg, Spinoza continued work on the Ethics and corresponded with scientists, philosophers, and theologians throughout Europe.[63] He also wrote and published his Theological Political Treatise in 1670, in defence of secular and constitutional government, and in support of Jan de Witt, the Grand Pensionary of the Netherlands, against the Stadholder, the Prince of Orange.[64] Leibniz visited Spinoza and claimed that Spinoza's life was in danger when supporters of the Prince of Orange murdered de Witt in 1672.[65] While published anonymously, the work did not long remain so, and de Witt's enemies characterized it as "forged in Hell by a renegade Jew and the Devil, and issued with the knowledge of Jan de Witt."[66] It was condemned in 1673 by the Synod of the Reformed Church and formally banned in 1674.[66]

Lens-grinding and optics[edit]
Spinoza earned a modest living from lens-grinding and instrument making, yet he was involved in important optical investigations of the day while living in Voorburg, through correspondence and friendships with scientist Christiaan Huygens and mathematician Johannes Hudde, including debate over microscope design with Huygens, favouring small objectives[67] and collaborating on calculations for a prospective 40 ft telescope which would have been one of the largest in Europe at the time.[68] The quality of Spinoza's lenses was much praised by Christiaan Huygens, among others.[69] In fact, his technique and instruments were so esteemed that Constantijn Huygens ground a "clear and bright" 42 ft. telescope lens in 1687 from one of Spinoza's grinding dishes, ten years after his death.[70] The exact type of lenses that Spinoza made are not known, but very likely included lenses for both the microscope and telescope. He was said by anatomist Theodor Kerckring to have produced an "excellent" microscope, the quality of which was the foundation of Kerckring's anatomy claims.[71] During his time as a lens and instrument maker, he was also supported by small but regular donations from close friends.[5]

The Hague[edit]
In 1670, Spinoza moved to The Hague where he lived on a small pension from Jan de Witt and a small annuity from the brother of his dead friend, Simon de Vries.[66] He worked on the Ethics, wrote an unfinished Hebrew grammar, began his Political Treatise, wrote two scientific essays ("On the Rainbow" and "On the Calculation of Chances"), and began a Dutch translation of the Bible (which he later destroyed).[66]

Spinoza chose for his device the Latin word "caute" ("cautiously"), inscribed beneath a rose, itself a symbol of secrecy.[11] "For, having chosen to write in a language that was so widely intelligible, he was compelled to hide what he had written."[11]

Spinoza was offered the chair of philosophy at the University of Heidelberg, but he refused it, perhaps because of the possibility that it might in some way curb his freedom of thought.[72]

In 1676, Spinoza met with Leibniz at The Hague for a discussion of his principal philosophical work, Ethics, which had been completed in 1676. This meeting was described in Matthew Stewart's The Courtier and the Heretic.[73]

Spinoza's health began to fail in 1676, and he died on 20 February 1677 at the age of 44.[74] His premature death was said to be due to lung illness, possibly silicosis as a result of breathing in glass dust from the lenses that he ground. Later, a shrine was made of his home in The Hague.[75]

Textbooks and encyclopaedias often depict Spinoza as a solitary soul who eked out a living as a lens grinder; in reality, he had many friends but kept his needs to a minimum.[5] He preached a philosophy of tolerance and benevolence. Anthony Gottlieb described him as living "a saintly life."[5] Reviewer M. Stuart Phelps noted, "No one has ever come nearer to the ideal life of the philosopher than Spinoza."[76] Harold Bloom wrote, "As a teacher of reality, he practised his own wisdom, and was surely one of the most exemplary human beings ever to have lived."[77] According to The New York Times: "In outward appearance he was unpretending, but not careless. His way of living was exceedingly modest and retired; often he did not leave his room for many days together. He was likewise almost incredibly frugal; his expenses sometimes amounted only to a few pence a day."[78] Bloom writes of Spinoza, "He appears to have had no sexual life."[77]

Spinoza also corresponded with Peter Serrarius, a radical Protestant and millennarian merchant. Serrarius was a patron to Spinoza after Spinoza left the Jewish community and even had letters sent and received for the philosopher to and from third parties. Spinoza and Serrarius maintained their relationship until Serrarius' death in 1669.[79] By the beginning of the 1660s, Spinoza's name became more widely known, and eventually Gottfried Leibniz[73] and Henry Oldenburg paid him visits, as stated in Matthew Stewart's The Courtier and the Heretic.[73] Spinoza corresponded with Oldenburg for the rest of his short life.

Writings and correspondence[edit]
The writings of René Descartes have been described as "Spinoza's starting point."[77] Spinoza's first publication was his geometric exposition (proofs using the geometric method on the model of Euclid with definitions, axioms, etc.) of Descartes's Parts I and II of Principles of Philosophy (1663). Spinoza has been associated with Leibniz and Descartes as "rationalists" in contrast to "empiricists."[80]

Spinoza engaged in correspondence from December 1664 to June 1665 with Willem van Blijenbergh, an amateur Calvinist theologian, who questioned Spinoza on the definition of evil. Later in 1665, Spinoza notified Oldenburg that he had started to work on a new book, the Theologico-Political Treatise, published in 1670. Leibniz disagreed harshly with Spinoza in his own manuscript "Refutation of Spinoza,"[81] but he is also known to have met with Spinoza on at least one occasion[73][80] (as mentioned above), and his own work bears some striking resemblances to specific important parts of Spinoza's philosophy (see: Monadology).

When the public reactions to the anonymously published Theologico-Political Treatise were extremely unfavourable to his brand of Cartesianism, Spinoza was compelled to abstain from publishing more of his works. Wary and independent, he wore a signet ring which he used to mark his letters and which was engraved with a rose and the word "caute" (Latin for "cautiously").[82]

The Ethics and all other works, apart from the Descartes' Principles of Philosophy and the Theologico-Political Treatise, were published after his death in the Opera Posthuma, edited by his friends in secrecy to avoid confiscation and destruction of manuscripts. The Ethics contains many still-unresolved obscurities and is written with a forbidding mathematical structure modelled on Euclid's geometry[5] and has been described as a "superbly cryptic masterwork."[77]

Philosophy[edit]
Substance, attributes, and modes[edit]
Main article: Philosophy of Baruch Spinoza
These are the fundamental concepts with which Spinoza sets forth a vision of Being, illuminated by his awareness of God. They may seem strange at first sight. To the question "What is?" he replies: "Substance, its attributes, and modes".

—?Karl Jaspers[83]
Spinoza argued that God exists and is abstract and impersonal.[5] Spinoza's view of God is what Charles Hartshorne describes as Classical Pantheism.[84] Spinoza has also been described as an "Epicurean materialist,"[77] specifically in reference to his opposition to Cartesian mind-body dualism. This view was held by Epicureans before him, as they believed that atoms with their probabilistic paths were the only substance that existed fundamentally.[85][86] Spinoza, however, deviated significantly from Epicureans by adhering to strict determinism, much like the Stoics before him, in contrast to the Epicurean belief in the probabilistic path of atoms, which is more in line with contemporary thought on quantum mechanics.[87][85] Spinoza's system imparted order and unity to the tradition of radical thought, offering powerful weapons for prevailing against "received authority." He contended that everything that exists in Nature (i.e., everything in the Universe) is one Reality (substance) and there is only one set of rules governing the whole of the reality which surrounds us and of which we are part. Spinoza viewed God and Nature as two names for the same reality,[77] namely a single, fundamental substance (meaning "that which stands beneath" rather than "matter") that is the basis of the universe and of which all lesser "entities" are actually modes or modifications, that all things are determined by Nature to exist and cause effects, and that the complex chain of cause and effect is understood only in part. His identification of God with nature was more fully explained in his posthumously published Ethics.[5] Spinoza's main contention with Cartesian mind–body dualism was that, if mind and body were truly distinct, then it is not clear how they can coordinate in any manner. Humans presume themselves to have free will, he argues, which is a result of their awareness of appetites that affect their minds, while being unable to understand the reasons why they want and act as they do.

Spinoza contends that "Deus sive Natura" is a being of infinitely many attributes, of which thought and extension are two. His account of the nature of reality, then, seems to treat the physical and mental worlds as intertwined, causally related, and deriving from the same substance. It is important to note here that, in Parts 3 through 4 of the Ethics, Spinoza describes how the human mind is affected by both mental and physical factors. He directly contests dualism. The universal substance emanates both body and mind; while they are different attributes, there is no fundamental difference between these aspects. This formulation is a historically significant solution to the mind–body problem known as neutral monism. Spinoza's system also envisages a God that does not rule over the universe by Providence in which God can make changes, but a God which itself is the deterministic system of which everything in nature is a part. Spinoza argues that "things could not have been produced by God in any other way or in any other order than is the case,";[88] he directly challenges a transcendental God which actively responds to events in the universe. Everything that has and will happen is a part of a long chain of cause and effect which, at a metaphysical level, humans are unable to change. No amount of prayer or ritual will sway God. Only knowledge of God, or the existence which humans inhabit, allows them to best respond to the world around them. Not only is it impossible for two infinite substances to exist (two infinities being absurd),[89] God—being the ultimate substance—cannot be affected by anything else, or else it would be affected by something else, and not be the fundamental substance.

Spinoza was a thoroughgoing determinist who held that absolutely everything that happens occurs through the operation of necessity. For him, even human behaviour is fully determined, with freedom being our capacity to know we are determined and to understand why we act as we do. By forming more "adequate" ideas about what we do and our emotions or affections, we become the adequate cause of our effects (internal or external), which entails an increase in activity (versus passivity). This means that we become both more free and more like God, as Spinoza argues in the Scholium to Prop. 49, Part II. However, Spinoza also held that everything must necessarily happen the way that it does. Therefore, humans have no free will. They believe, however, that their will is free. This illusionary perception of freedom stems from our human consciousness, experience, and indifference to prior natural causes. Humans think they are free but they ?dream with their eyes open?. For Spinoza, our actions are guided entirely by natural impulses. In his letter to G. H. Schuller (Letter 58), he wrote: "men are conscious of their desire and unaware of the causes by which [their desires] are determined."[90]

This picture of Spinoza's determinism is ever more illuminated through reading this famous quote in Ethics: ?the infant believes that it is by free will that it seeks the breast; the angry boy believes that by free will he wishes vengeance; the timid man thinks it is with free will he seeks flight; the drunkard believes that by a free command of his mind he speaks the things which when sober he wishes he had left unsaid. … All believe that they speak by a free command of the mind, whilst, in truth, they have no power to restrain the impulse which they have to speak.?[91] Thus for Spinoza morality and ethical judgement like choice is predicated on an illusion. For Spinoza, ?Blame? and ?Praise? are non existent human ideals only fathomable in the mind because we are so acclimatized to human consciousness interlinking with our experience that we have a false ideal of choice predicated upon this.

Spinoza's philosophy has much in common with Stoicism inasmuch as both philosophies sought to fulfil a therapeutic role by instructing people how to attain happiness. However, Spinoza differed sharply from the Stoics in one important respect: he utterly rejected their contention that reason could defeat emotion. On the contrary, he contended, an emotion can only be displaced or overcome by a stronger emotion. For him, the crucial distinction was between active and passive emotions, the former being those that are rationally understood and the latter those that are not. He also held that knowledge of true causes of passive emotion can transform it to an active emotion, thus anticipating one of the key ideas of Sigmund Freud's psychoanalysis.[92]

Ethical philosophy[edit]
Spinoza shared ethical beliefs with ancient Epicureans, in renouncing ethics beyond the material world, although Epicureans focused more on physical pleasure and Spinoza more on emotional wellbeing.[93] Encapsulated at the start in his Treatise on the Improvement of the Understanding (Tractatus de intellectus emendatione) is the core of Spinoza's ethical philosophy, what he held to be the true and final good. Spinoza held good and evil to be relative concepts, claiming that nothing is intrinsically good or bad except relative to a particularity. Things that had classically been seen as good or evil, Spinoza argued, were simply good or bad for humans. Spinoza believes in a deterministic universe in which "All things in nature proceed from certain [definite] necessity and with the utmost perfection." Nothing happens by chance in Spinoza's world, and nothing is contingent.

Given Spinoza's insistence on a completely ordered world where "necessity" reigns, Good and Evil have no absolute meaning. The world as it exists looks imperfect only because of our limited perception.

Spinoza's "Ethics"[edit]
Main article: Ethics (Spinoza)

The opening page of Spinoza's magnum opus, Ethics
In the universe anything that happens comes from the essential nature of objects, or of God or Nature. According to Spinoza, reality is perfection. If circumstances are seen as unfortunate it is only because of our inadequate conception of reality. While components of the chain of cause and effect are not beyond the understanding of human reason, human grasp of the infinitely complex whole is limited because of the limits of science to empirically take account of the whole sequence. Spinoza also asserted that sense perception, though practical and useful, is inadequate for discovering truth. His concept of "conatus" states that human beings' natural inclination is to strive toward preserving an essential being, and asserts that virtue/human power is defined by success in this preservation of being by the guidance of reason as one's central ethical doctrine. According to Spinoza, the highest virtue is the intellectual love or knowledge of God/Nature/Universe.

Also in the "Ethics",[94] Spinoza discusses his beliefs about what he considers to be the three kinds of knowledge that come with perceptions. The first kind of knowledge he writes about is the knowledge of experiences. More precisely, this first type of knowledge can be known as the knowledge of things that could be “mutilated, confused, and without order.” [95] Another explanation of what the first knowledge can be is that it is the knowledge of dangerous reasoning. Dangerous reason lacks any type of rationality, and causes the mind to be in a “passive” state. This type of “passive mind” that Spinoza writes about in the earlier books of The Ethics is a state of the mind in which adequate causes become passions. Spinoza’s second knowledge involves reasoning plus emotions. He explains that this knowledge is had by the rationality of any adequate causes that have to do with anything common to the human mind. An example of this could be anything that is classified as being of imperfect virtue. Imperfect virtues are seen as those which are incomplete. Many philosophers, such as Thomas Aquinas and Aristotle, would compare imperfect virtue to pagan virtue. Spinoza defines the third and final knowledge as the knowledge of God, which requires rationality and reason of the mind. In more detail, Spinoza uses this type of knowledge to join together the essence of God with the individual essence. This knowledge is also formed from any adequate causes that include perfect virtue. [95]

In the final part of the "Ethics", his concern with the meaning of "true blessedness", and his explanation of how emotions must be detached from external causes in order to master them, foreshadow psychological techniques developed in the 1900s. His concept of three types of knowledge—opinion, reason, intuition—and his assertion that intuitive knowledge provides the greatest satisfaction of mind, lead to his proposition that the more we are conscious of ourselves and Nature/Universe, the more perfect and blessed we are (in reality) and that only intuitive knowledge is eternal.

History of reception[edit]
Pantheist, panentheist, or atheist?[edit]
Main article: Spinozism
See also: Pantheism controversy

An unfavorable engraving depiction of philosopher Spinoza, captioned in Latin, "A Jew and an Atheist".
It is a widespread belief that Spinoza equated God with the material universe. He has therefore been called the "prophet"[96] and "prince"[97] and most eminent expounder of pantheism. More specifically, in a letter to Henry Oldenburg he states, "as to the view of certain people that I identify God with Nature (taken as a kind of mass or corporeal matter), they are quite mistaken".[98] For Spinoza, our universe (cosmos) is a mode under two attributes of Thought and Extension. God has infinitely many other attributes which are not present in our world.

According to German philosopher Karl Jaspers (1883–1969), when Spinoza wrote in Deus sive Natura (Latin for 'God or Nature'), Spinoza meant God was natura naturans (nature doing what nature does; literally, 'nature naturing'), not natura naturata (nature already created; literally, 'nature natured'). Jaspers believed that Spinoza, in his philosophical system, did not mean to say that God and Nature are interchangeable terms, but rather that God's transcendence was attested by his infinitely many attributes, and that two attributes known by humans, namely Thought and Extension, signified God's immanence.[99] Even God under the attributes of thought and extension cannot be identified strictly with our world. That world is of course "divisible"; it has parts. But Spinoza said, "no attribute of a substance can be truly conceived from which it follows that the substance can be divided", meaning that one cannot conceive an attribute in a way that leads to division of substance. He also said, "a substance which is absolutely infinite is indivisible" (Ethics, Part I, Propositions 12 and 13).[100] Following this logic, our world should be considered as a mode under two attributes of thought and extension. Therefore, according to Jaspers, the pantheist formula "One and All" would apply to Spinoza only if the "One" preserves its transcendence and the "All" were not interpreted as the totality of finite things.[99]

Martial Guéroult (1891–1976) suggested the term "panentheism", rather than "pantheism" to describe Spinoza's view of the relation between God and the world. The world is not God, but it is, in a strong sense, "in" God. Not only do finite things have God as their cause; they cannot be conceived without God.[100] However, American panentheist philosopher Charles Hartshorne (1897–2000) insisted on the term Classical Pantheism to describe Spinoza's view.[84]

In 1785, Friedrich Heinrich Jacobi published a condemnation of Spinoza's pantheism, after Gotthold Lessing was thought to have confessed on his deathbed to being a "Spinozist", which was the equivalent in his time of being called an atheist. Jacobi claimed that Spinoza's doctrine was pure materialism, because all Nature and God are said to be nothing but extended substance. This, for Jacobi, was the result of Enlightenment rationalism and it would finally end in absolute atheism. Moses Mendelssohn disagreed with Jacobi, saying that there is no actual difference between theism and pantheism. The issue became a major intellectual and religious concern for European civilization at the time.

The attraction of Spinoza's philosophy to late 18th-century Europeans was that it provided an alternative to materialism, atheism, and deism. Three of Spinoza's ideas strongly appealed to them:

the unity of all that exists;
the regularity of all that happens;
the identity of spirit and nature.[101]
By 1879, Spinoza’s pantheism was praised by many, but was considered by some to be alarming and dangerously inimical.[102]

Spinoza's "God or Nature" (Deus sive Natura) provided a living, natural God, in contrast to Isaac Newton's first cause argument and the dead mechanism of Julien Offray de La Mettrie's (1709–1751) work, Man a Machine (L'homme machine). Coleridge and Shelley saw in Spinoza's philosophy a religion of nature.[5] Novalis called him the "God-intoxicated man".[77][103] Spinoza inspired the poet Shelley to write his essay "The Necessity of Atheism".[77]

Spinoza was considered to be an atheist because he used the word "God" (Deus) to signify a concept that was different from that of traditional Judeo–Christian monotheism. "Spinoza expressly denies personality and consciousness to God; he has neither intelligence, feeling, nor will; he does not act according to purpose, but everything follows necessarily from his nature, according to law...."[104] Thus, Spinoza's cool, indifferent God[105] is the antithesis to the concept of an anthropomorphic, fatherly God who cares about humanity.

According to the Stanford Encyclopedia of Philosophy, Spinoza's God is an “infinite intellect” (Ethics 2p11c) — all knowing (2p3), and capable of loving both himself—and us, insofar as we are part of his perfection (5p35c). And if the mark of a personal being is that it is one towards which we can entertain personal attitudes, then we should note too that Spinoza recommends amor intellectualis dei (the intellectual love of God) as the supreme good for man (5p33). However, the matter is complex. Spinoza's God does not have free will (1p32c1), he does not have purposes or intentions (1 appendix), and Spinoza insists that “neither intellect nor will pertain to the nature of God” (1p17s1). Moreover, while we may love God, we need to remember that God is really not the kind of being who could ever love us back. “He who loves God cannot strive that God should love him in return,” says Spinoza (5p19).[106]

Steven Nadler suggests that settling the question of Spinoza's atheism or pantheism depends on an analysis of attitudes. If pantheism is associated with religiosity, then Spinoza is not a pantheist, since Spinoza believes that the proper stance to take towards God is not one of reverence or religious awe, but instead one of objective study and reason, since taking the religious stance would leave one open to the possibility of error and superstition.[107]

Comparison to Eastern philosophies[edit]
Similarities between Spinoza's philosophy and Eastern philosophical traditions have been discussed by many authors. The 19th-century German Sanskritist Theodore Goldstücker was one of the early figures to notice the similarities between Spinoza's religious conceptions and the Vedanta tradition of India, writing that Spinoza's thought was

... a western system of philosophy which occupies a foremost rank amongst the philosophies of all nations and ages, and which is so exact a representation of the ideas of the Vedanta, that we might have suspected its founder to have borrowed the fundamental principles of his system from the Hindus, did his biography not satisfy us that he was wholly unacquainted with their doctrines... We mean the philosophy of Spinoza, a man whose very life is a picture of that moral purity and intellectual indifference to the transitory charms of this world, which is the constant longing of the true Vedanta philosopher... comparing the fundamental ideas of both we should have no difficulty in proving that, had Spinoza been a Hindu, his system would in all probability mark a last phase of the Vedanta philosophy.[108][109]

Max Muller, in his lectures, noted the striking similarities between Vedanta and the system of Spinoza, saying "the Brahman, as conceived in the Upanishads and defined by Sankara, is clearly the same as Spinoza's 'Substantia'."[110] Helena Blavatsky, a founder of the Theosophical Society also compared Spinoza's religious thought to Vedanta, writing in an unfinished essay "As to Spinoza's Deity—natura naturans—conceived in his attributes simply and alone; and the same Deity—as natura naturata or as conceived in the endless series of modifications or correlations, the direct out-flowing results from the properties of these attributes, it is the Vedantic Deity pure and simple."[111]

Spinoza's reception in the 19th and 20th centuries[edit]
Europe in the 19th and 20th centuries grew even more interested in Spinoza, often from a left-wing or Marxist perspective. Karl Marx liked Spinoza's account of the universe, interpreting it as materialistic.[5] Notable philosophers Louis Althusser, Gilles Deleuze, Antonio Negri and Étienne Balibar have each drawn upon Spinoza's philosophy. Deleuze's doctoral thesis, published in 1968, calls him "the prince of philosophers".[112] Nietzsche esteemed few philosophers, but he esteemed Spinoza.[113][114][115] However, Nietzsche never read Spinoza's works themselves, but learned about Spinoza from Kuno Fischer's History of Modern Philosophy.[116]

When George Santayana graduated from college, he published an essay, "The Ethical Doctrine of Spinoza", in The Harvard Monthly.[117] Later, he wrote an introduction to Spinoza's Ethics and "De intellectus emendatione".[118] In 1932, Santayana was invited to present an essay (published as "Ultimate Religion")[119] at a meeting at The Hague celebrating the tricentennial of Spinoza's birth. In Santayana's autobiography, he characterized Spinoza as his "master and model" in understanding the naturalistic basis of morality.[120]

Spinoza's religious criticism and its effect on the philosophy of language[edit]

Tractatus Theologico-Politicus
Philosopher Ludwig Wittgenstein evoked Spinoza with the title (suggested to him by G. E. Moore) of the English translation of his first definitive philosophical work, Tractatus Logico-Philosophicus, an allusion to Spinoza's Tractatus Theologico-Politicus. Elsewhere, Wittgenstein deliberately borrowed the expression sub specie aeternitatis from Spinoza (Notebooks, 1914-16, p. 83). The structure of his Tractatus Logico-Philosophicus does have some structural affinities with Spinoza's Ethics (though, admittedly, not with the latter's own Tractatus) in erecting complex philosophical arguments upon basic logical assertions and principles. Furthermore, in propositions 6.4311 and 6.45 he alludes to a Spinozian understanding of eternity and interpretation of the religious concept of eternal life, stating that "If by eternity is understood not eternal temporal duration, but timelessness, then he lives eternally who lives in the present." (6.4311) "The contemplation of the world sub specie aeterni is its contemplation as a limited whole." (6.45)

Leo Strauss dedicated his first book, Spinoza's Critique of Religion, to an examination of the latter's ideas. In the book, Strauss identified Spinoza as part of the tradition of Enlightenment rationalism that eventually produced Modernity. Moreover, he identifies Spinoza and his works as the beginning of Jewish Modernity.[77] More recently Jonathan Israel argued that, from 1650 to 1750, Spinoza was "the chief challenger of the fundamentals of revealed religion, received ideas, tradition, morality, and what was everywhere regarded, in absolutist and non-absolutist states alike, as divinely constituted political authority."[121]

Spinoza in literature, art, and popular culture[edit]
Spinoza has had influence beyond the confines of philosophy.

On the Chair's table in the Dutch Parliament, Spinoza's Tractatus theologico-politicus is one of three books thought to be most representative of the beliefs and ethics of the Dutch people; the other two are the Bible and the Quran.[122]
The 19th century novelist George Eliot produced her own translation of the Ethics, the first known English translation of it. Eliot liked Spinoza's vehement attacks on superstition.[5]
In his autobiography "From My Life: Poetry and Truth", Goethe recounts the way in which Spinoza's Ethics calmed the sometimes unbearable emotional turbulence of his youth. Goethe later displayed his grasp of Spinoza's metaphysics in a fragmentary elucidation of some Spinozist ontological principles entitled Study After Spinoza.[123] Moreover, he cited Spinoza alongside Shakespeare and Carl Linnaeus as one of the three strongest influences on his life and work.[124]
The 20th century novelist W. Somerset Maugham alluded to one of Spinoza's central concepts with the title of his novel Of Human Bondage.[citation needed]
In the early Star Trek episode, "Where No Man Has Gone Before", the antagonist, Gary Mitchell is seen reading Spinoza, and Mitchell's remark regarding his ease in comprehending Spinoza implies that his intellectual capacity is increasing dramatically. The dialogue indicates that Captain Kirk is familiar with Spinoza's work, perhaps as part of his studies at Starfleet Academy.
Albert Einstein named Spinoza as the philosopher who exerted the most influence on his world view (Weltanschauung). Spinoza equated God (infinite substance) with Nature, consistent with Einstein's belief in an impersonal deity. In 1929, Einstein was asked in a telegram by Rabbi Herbert S. Goldstein whether he believed in God. Einstein responded by telegram: "I believe in Spinoza's God who reveals himself in the orderly harmony of what exists, not in a God who concerns himself with the fates and actions of human beings."[125][126]
Spinoza's pantheism has also influenced environmental theory; Arne Næss, the father of the deep ecology movement, acknowledged Spinoza as an important inspiration.[citation needed]
The Argentine writer Jorge Luis Borges was greatly influenced by Spinoza's world view. Borges makes allusions to the philosopher's work in many of his poems and short stories, as does Isaac Bashevis Singer in his short story The Spinoza of Market Street.[127]
The title character of Hoffman's Hunger, the fifth novel by the Dutch novelist Leon de Winter, reads and comments upon the Tractatus de Intellectus Emendatione over the course of the novel.
Spinoza has been the subject of numerous biographies and scholarly treatises.[103][128][129][130]
Spinoza is an important historical figure in the Netherlands, where his portrait was featured prominently on the Dutch 1000-guilder banknote, legal tender until the euro was introduced in 2002. The highest and most prestigious scientific award of the Netherlands is named the Spinozaprijs (Spinoza prize). Spinoza was included in a 50 theme canon that attempts to summarise the history of the Netherlands.[131]
In the sequel to Eric Flint's alternate-history novel, 1632, a Jewish man and his wife are killed during an attack on Amsterdam, leaving behind a less-than-year-old son. The identity of the child is quickly revealed to be the infant Spinoza himself.[citation needed]
The 2008 play "New Jerusalem", by David Ives, is based on the cherem (ban, shunning, ostracism, expulsion or excommunication) issued against Spinoza by the Talmud Torah congregation in Amsterdam in 1656, and events leading to it. Ives speculates that Spinoza was excommunicated in order to appease Dutch authorities who threatened to expel Amsterdam's Jews because of Spinoza's anti-religious activities amongst the city's Christian community.[132]
In Bento's Sketchbook (2011), the writer John Berger combines extracts from Spinoza, sketches, memoir, and observations in a book that contemplates the relationship of materialism to spirituality. According to Berger, what could be seen as a contradiction "is beautifully resolved by Spinoza, who shows that it is not a duality, but in fact an essential unity."[133]
Leopold Bloom is shown several times to be an admirer of Spinoza in James Joyce's Ulysses. Thoughts from Spinoza, an anthology, is represented on Bloom's bookshelf towards the end of the novel.[134]
Bibliography[edit]
c.?1660. Korte Verhandeling van God, de mensch en deszelvs welstand (A Short Treatise on God, Man and His Well-Being).
1662. Tractatus de Intellectus Emendatione (On the Improvement of the Understanding).
1663. Principia philosophiae cartesianae (The Principles of Cartesian Philosophy, translated by Samuel Shirley, with an Introduction and Notes by Steven Barbone and Lee Rice, Indianapolis, 1998). Gallica (in Latin).
1670. Tractatus Theologico-Politicus (A Theologico-Political Treatise).
1675–76. Tractatus Politicus (unfinished) (PDF version)
1677. Ethica Ordine Geometrico Demonstrata (The Ethics, finished 1674, but published posthumously)
1677. Compendium grammatices linguae hebraeae (Hebrew Grammar).[135]
Morgan, Michael L. (ed.), 2002. Spinoza: Complete Works, with the Translation of Samuel Shirley, Indianapolis/Cambridge: Hackett Publishing Company. ISBN 978-0-87220-620-5.
Edwin Curley (ed.), 1985–2016. The Collected Works of Spinoza (two volumes), Princeton: Princeton University Press.
Spruit, Leen and Pina Totaro, 2011. The Vatican Manuscript of Spinoza’s Ethica, Leiden: Brill.